### ISSUE TITLE
CodePush isn't compatible with cordova-plugin-wkwebview-engine-localhost

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/cordova-plugin-code-push#134]
We added support for the `cordova-plugin-wkwebview-engine` plugin, but that unfortunately doesn't support iOS8. For folks that want to use WKWebView **and** have iOS 8 support, one option is to use the `cordova-plugin-wkwebview-engine-localhost` plugin. This plugin works by spinning up a local web server to serve the app content, which allows your app to work around the limitation that iOS 8 has for loading file-based content into `WKWebView`. Unfortunately, CodePush isn't compatible with this plugin, due to the fact that it modified the start page in the app's `config.xml` file, and also requires all webview redirections to be routed through its `http://localhost` endpoint in order to actually work on iOS 8.

I'm opening up this issue to track the work needed to add support for this scenario.

**Comment by kenvunz** [comment]
@lostintangent any ETA for this support?

Cheers

**Comment by northkode** [comment]
definitely would like this aswell..

**Comment by northkode** [comment]
@lostintangent i have my ios developer looking into this.. 
any think you can do to point us in the right direction as to what you think your approach might be and maybe we can fix it and release a pull request?

**Comment by silhouettes** [comment]
Basically, the tricky thing is that the `cordova-plugin-wkwebview-engine-localhost` plugin mounts everything to a URL path invisibly, which makes it difficult for other plugins that use local file paths to detect this or to construct these URL strings. Any fix would likely require heavy special-casing.

For CodePush, there are two areas where this is an issue:

1. Before we install a new package, we validate that the start page specified in the `config.xml` exists in the package. Because the start page in the `config.xml` is re-written by the `cordova-plugin-wkwebview-engine` from something like `index.html` to something like `http://localhost:0/index.html`, we end up attempting to validate that something like `codepush/updates/http://localhost:0/index.html` exists in the downloaded package, which breaks ([here](https://github.com/Microsoft/cordova-plugin-code-push/blob/5adfe14c430f5cbc688eecf39c27852250df9dd3/src/ios/CodePush.m#L191)). This should be easy to fix by special-casing when `cordova-plugin-wkwebview-engine`  is in use and stripping out the `localhost` portion.
1. After the installation, if we want to redirect to the new package immediately, we attempt to redirect to the file path (something like `codepush/updates/index.html`), instead of the URL path expected by   `cordova-plugin-wkwebview-engine` (something like `http://localhost:123/codepush/updates/index.html?token=asdfasdf`), which breaks ([here](https://github.com/Microsoft/cordova-plugin-code-push/blob/5adfe14c430f5cbc688eecf39c27852250df9dd3/src/ios/CodePush.m#L364)). This is more tricky, as it isn't immediately clear how to construct the port at the beginning of the URL, and the token at the end of it.

Either way, all affected cases end up [here](https://github.com/Microsoft/cordova-plugin-code-push/blob/5adfe14c430f5cbc688eecf39c27852250df9dd3/src/ios/CodePush.m#L349), where there needs to be an intelligent way to detect the use of the local web server, and translate to/from file paths/URL paths.

As you can see, it's tricky, but you are more than welcome to submit a pull request for this and we look forward to any clever ideas you may have!

**Comment by northkode** [comment]
We aren't currently use the webserver you are referring too.
We are using https://github.com/Telerik-Verified-Plugins/WKWebView

This does not make the changes to the config file index file etc that you mentioned.

**Comment by northkode** [comment]
inside his code he sets
`
    // Note: the embedded webserver is still needed for iOS 9. It's not needed to load index.html,
    //       but we need it to ajax-load files (file:// protocol has no origin, leading to CORS issues).
    NSString *directoryPath = myMainViewController.wwwFolderName;
`

therefore.. i wonder if we can leverage the mainViewViewController.wwwFolderName and just set it to the path of the latest downloaded package

**Comment by northkode** [comment]
Updated version of this plugin https://github.com/Telerik-Verified-Plugins/WKWebView
works with your code on ios!!  We just updated the plugin and bam, ios updates and the local server points to the right updated build directory @silhouettes

**Comment by silhouettes** [comment]
Great!!! Thanks so much for investigating this @northkode :) @kenvunz, for iOS 8 + WKWebView support, could your issue possibly be resolved by switching to this plugin?

**Comment by silhouettes** [comment]
I'm closing this as it seems to be solved by using https://github.com/Telerik-Verified-Plugins/WKWebView. Feel free to re-open it if there are any other issues or support for `cordova-plugin-wkwebview-engine` is still needed!

**Comment by thomasbaggio** [comment]
Hi @silhouettes we still have the problem using this plugin: cordova-labs-local-webserver  (and the official WKWebView Phonegap plugin)

**Comment by silhouettes** [comment]
Hi @thomasbaggio, do you mind filing this as a separate issue?
