### ISSUE TITLE
Updates are always "pending"

### ISSUE THREAD

**Issue by jbarker7** [Microsoft/cordova-plugin-code-push#368]
### Description

I put the code in place to do over the air updates, and it appears that the code does push, but every time I run:
`code-push deployment ls XXXXX`

I get:

Active: 0% (1 of XXX)
Total: 0 (XXX pending)

The "pending" never switches to success (but I do see the app update?)

### Reproduction

I am using an Ionic app (+Redux) have put in my app.component.ts:

`platform.ready().then(() => {
  this.ngRedux.dispatch(update());
});`

update() is in another file:
```
  const changeUpdateStatus = status => ({
    type: 'UPDATE_STATUS',
    payload: status
  });
  export const update = () => dispatch => {
    dispatch(changeUpdateStatus('INIT'));

    let sync = () => {
      let codePush = (<any>window).codePush;
      let SyncStatus = (<any>window).SyncStatus;

      if(!codePush){
        throw new Error('Code push not installed');
      };
      const keys = {
        'iOS': env.codePushKeys.ios,
        'Android': env.codePushKeys.android
      };
      const deploymentKey = keys[(<any>window).device.platform];
      console.log('Trying to sync code push using key: ', deploymentKey);
      
      codePush.sync(
        (status) => {
          console.log('status:', status);
          switch (status) {
            case SyncStatus.UPDATE_INSTALLED:
              dispatch(changeUpdateStatus('DONE'));
            break;
            case SyncStatus.CHECKING_FOR_UPDATE:
              dispatch(changeUpdateStatus('CHECKING'));
            break;
            case SyncStatus.DOWNLOADING_PACKAGE:
              dispatch(changeUpdateStatus('DOWNLOADING'));
            break;
            case SyncStatus.INSTALLING_UPDATE:
              dispatch(changeUpdateStatus('INSTALLING'));
            break;
            default: //ERROR, UP_TO_DATE
              dispatch(changeUpdateStatus('DONE'));
            break;
          }
        },
        {
          deploymentKey,
          installMode: (<any>window).InstallMode.IMMEDIATE,
          mandatoryInstallMode: (<any>window).InstallMode.IMMEDIATE
        },
        (downloadProgress) => {
          // TODO: Add progress to state.
          if (downloadProgress) {
              console.log("Downloading " + downloadProgress.receivedBytes + " of " + downloadProgress.totalBytes);
          }
        }
      );
    }  
    sync() && onEvent("resume").then(sync).catch( (e) => {
      dispatch(changeUpdateStatus('DONE'));
      analytics.logError(e);
    });
  };
```
### Additional Information

* cordova-plugin-code-push version: 1.11.0

* List of installed plugins:
`
    <plugin name="cordova-plugin-camera" spec="^3.0.0" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
    <plugin name="cordova-plugin-contacts" spec="^3.0.0" />
    <plugin name="cordova-plugin-camera-preview" spec="^0.9.0" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.0" />
    <plugin name="cordova-plugin-background-upload" spec="^1.0.6" />
    <plugin name="cordova-plugin-media-capture" spec="^3.0.0" />
    <plugin name="cordova-sms-plugin" spec="^0.1.11" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
    <plugin name="cordova-plugin-code-push" spec="~1.11.0" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="phonegap-plugin-push" spec="^2.1.2">
        <variable name="FCM_VERSION" value="11.0.1" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.2.0">
        <variable name="ANDROID_SUPPORT_VERSION" value="26.+" />
    </plugin>
    <plugin name="cordova-plugin-globalization" spec="^1.0.7" />
    <plugin name="cordova-plugin-android-permissions" spec="^1.0.0" />
`

* Cordova version: 7.1.0

* iOS/Android/Windows version: All

* Does this reproduce on a debug build or release build? Yes

* Does this reproduce on a simulator, or only on a physical device? Yes

**Comment by iTOYS** [comment]
Hi @jbarker7,
Thanks for reporting.

Do you have problem with installs or only with `code-push-cli` status? Do you have logs from `syncCallback`?

Thanks.

**Comment by jbarker7** [comment]
It appears OTA updates are not working either - not getting them on my phone.
![capture](https://user-images.githubusercontent.com/182973/36294405-8163da86-12ae-11e8-969f-76109d5291e8.PNG)

**Comment by iTOYS** [comment]
Weird, could you please add [syncErrback](https://github.com/Microsoft/cordova-plugin-code-push#codepushsync) and catch result?

Also, could you debug your extension locally? Any logs there?

**Comment by svekl** [comment]
Hi @jbarker7, can you, please, try new plugin version? I think it can be related to same issue that is fixed in this release.

**Comment by jbarker7** [comment]
Which version incorporated the fix?

**Comment by iTOYS** [comment]
@jbarker7 
Could you please check new release of plugin(1.11.6)?

**Comment by jbarker7** [comment]
Ok, so I installed 1.11.6.  So this is really strange.  Some users report to have the new update, others do not (for instance, I do not).  However, everyone still shows as "pending"- no idea why this is happening.

![image](https://user-images.githubusercontent.com/182973/36355163-832850f8-14ad-11e8-921e-b577ae497479.png)

**Comment by iTOYS** [comment]
@jbarker7 
Unfortunately, application reinstall required to fix this issue.
The simplest way its publish new version of the application to store.

Thanks!

**Comment by jbarker7** [comment]
That's what we did?  We released a completely new version to the app store... still have this problem.

**Comment by GoCac** [comment]
Maybe you fail to call notifyApplicationReady(), which should be called after UPDATE_INSTALLED. It effectively reports back to Code Push that the update was successful.
See more [notifyApplicationReady](https://github.com/Microsoft/cordova-plugin-code-push#codepushnotifyapplicationready)
