### ISSUE TITLE
codepush.sync downloads however refresh causes index.html 404

### ISSUE THREAD

**Issue by chazguerrero** [Microsoft/cordova-plugin-code-push#443]
### Description

When code push sync happens, update installs correctly. However after successful download when restarted the index.html 404s

```text
http://localhost:8080/Users/usr/Library/Developer/CoreSimulator/Devices/D152D9AC-B312-4C18-9428-0D1XXXXXX/data/Containers/Data/Application/A6CC2792-8B97-43A2-8B16-7XXXXXLibrary/NoCloud/codepush/deploy/versions/37df80531878b13b5231d8b408a6683460a5092aa8c4f5148064508f024a3363/www/index.html
Failed to load resource: the server responded with a status of 404 (Not Found)
```

I downloaded the zip from app center and the html file is there
### Reproduction

create new project

Ionic CLI version 4.1.1
```bash
    $ ionic start myApp tabs --type=angular
    $ cordova plugin add cordova-plugin-code-push@latest
    $ npm install --save @ionic-native/code-push
```
update the app module  and component.ts
``` javascript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule, RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CodePush } from '@ionic-native/code-push';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [
    StatusBar,
    SplashScreen,
    CodePush,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

import { Component } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { CodePush } from '@ionic-native/code-push';

// declare const codePush: any;
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {



  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
    private codePush: CodePush
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.codePush.sync().subscribe((syncStatus) => alert(syncStatus));
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });
  }
}


build project and deploy to emulator or device
```bash
   $ ionic cordova run ios
```

make a change to the app and push to appcenter

```bash
    $ ionic build
    $  appcenter codepush release-cordova -a org/CodePushExample -d Development --description "testing" -m
```

now after the phone downloads the update i get the below error
http://localhost:8080/Users/usr/Library/Developer/CoreSimulator/Devices/D152D9AC-B312-4C18-9428-0D1XXXXXX/data/Containers/Data/Application/A6CC2792-8B97-43A2-8B16-7XXXXXLibrary/NoCloud/codepush/deploy/versions/37df80531878b13b5231d8b408a6683460a5092aa8c4f5148064508f024a3363/www/index.html
Failed to load resource: the server responded with a status of 404 (Not Found)

```


### Additional Information

packagejson
```javascript
{
  "name": "CodePushSample",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~6.1.1",
    "@angular/core": "~6.1.1",
    "@angular/forms": "~6.1.1",
    "@angular/http": "~6.1.1",
    "@angular/platform-browser": "~6.1.1",
    "@angular/platform-browser-dynamic": "~6.1.1",
    "@angular/router": "~6.1.1",
    "@ionic-native/code-push": "^4.5.2",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/angular": "4.0.0-beta.5",
    "code-push": "^2.0.6",
    "cordova-android": "^7.0.0",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-appcenter-analytics": "^0.1.8",
    "cordova-plugin-appcenter-crashes": "^0.1.8",
    "cordova-plugin-appcenter-shared": "^0.1.8",
    "cordova-plugin-code-push": "^1.11.12",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-transfer": "^1.6.3",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.1.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-zip": "^3.1.0",
    "core-js": "^2.5.3",
    "rxjs": "6.2.2",
    "rxjs-compat": "^6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.7.2",
    "@angular-devkit/build-angular": "~0.7.2",
    "@angular-devkit/core": "~0.7.2",
    "@angular-devkit/schematics": "~0.7.2",
    "@angular/cli": "~6.1.1",
    "@angular/compiler": "~6.1.1",
    "@angular/compiler-cli": "~6.1.1",
    "@angular/language-service": "~6.1.1",
    "@ionic/lab": "1.0.8",
    "@ionic/ng-toolkit": "^1.0.0",
    "@ionic/schematics-angular": "^1.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.2",
    "codelyzer": "~4.4.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-code-push": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-appcenter-analytics": {},
      "cordova-plugin-appcenter-crashes": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}
```
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.codepushexample" version="0.0.3" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>CodePushSample</name>
    <description>CodePush Example</description>
    <author email="chaz" href="http://www.test.com/">Team</author>
    <content src="./index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <preference name="APP_SECRET" value="b249bf9c-e8e6-40ba-b178-XXXXXXXXX" />
        <preference name="CodePushDeploymentKey" value="ynmYHIm_XXXXXXXXXXXXX" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-file" spec="^4.3.3" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.6.3" />
    <plugin name="cordova-plugin-zip" spec="^3.1.0" />
    <plugin name="cordova-plugin-code-push" spec="^1.11.12" />
    <plugin name="cordova-plugin-appcenter-analytics" spec="^0.1.8" />
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.8" />
    <engine name="ios" spec="^4.5.5" />
    <engine name="android" spec="^7.0.0" />
</widget>

```

* cordova-plugin-code-push version: 
* List of installed plugins:
* Cordova version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? Only tried on debug builds
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @chazguerrero ,
Thanks for reporting!

Could you please clarify have you used liveRelaod feature of Ionic during update?
If yes, have you tried to update your app without LiveReload? Possible in release mode.

Thanks,
Alexander

**Comment by chazguerrero** [comment]
@alexandergoncharov Hi, 
I'm using the emulator without live reload so I can see it pull the new update with codepush.
I've also deployed a version to appcenter and installed on an ios device.

Both cause the issue. Let me know if theres any additional info i can give you!

**Comment by chazguerrero** [comment]
@alexandergoncharov I got it working :-) 

I had to remove 3 plugins and reinstall them as latest

- cordova-plugin-file
- cordova-plugin-file-transfer
- cordova-plugin-zip

**Comment by rromantp** [comment]
> @alexandergoncharov I got it working :-)
> 
> I had to remove 3 plugins and reinstall them as latest
> 
> * cordova-plugin-file
> * cordova-plugin-file-transfer
> * cordova-plugin-zip

@chazguerrero can you tell us what version you installed to get it working please

**Comment by gulullu** [comment]
> @alexandergoncharov I got it working :-)
> 
> I had to remove 3 plugins and reinstall them as latest
> 
> * cordova-plugin-file
> * cordova-plugin-file-transfer
> * cordova-plugin-zip

I have this issue too, but not resolved when I removed the  plugins and  reinstall them, can you tell me  what version you installed please?
