### ISSUE TITLE
Cordova 9.0 install errors

### ISSUE THREAD

**Issue by Sfinx** [microsoft/cordova-plugin-code-push#551]
Why codepush is still depends on ancient  cordova-plugin-file@4.3.3 & cordova-plugin-compat ?

```
rus@Shiva:~/test$ cordova -v
9.0.0 (cordova-lib@9.0.1)
rus@Shiva:~/test$ cordova create myApp org.apache.cordova.myApp myApp
Creating a new cordova project.
rus@Shiva:~/test$ cd myApp/
rus@Shiva:~/test/myApp$ cordova platform add android
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: org.apache.cordova.myApp
	Name: myApp
	Activity: MainActivity
	Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
rus@Shiva:~/test/myApp$ cordova plugin add cordova-plugin-code-push
Installing "cordova-plugin-code-push" for android
Installing "code-push" for android
Installing "cordova-plugin-dialogs" for android
Installing "cordova-plugin-device" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-code-push to package.json
Adding the cordova-plugin-file@4.3.3... 
Installing "cordova-plugin-file" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 8.0.0, failed version requirement: 
      <6.3.0
Skipping 'cordova-plugin-compat' for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
        
Adding cordova-plugin-file to package.json
Adding the cordova-plugin-file-transfer@1.6.3... 
Installing "cordova-plugin-file-transfer" for android
Plugin dependency "cordova-plugin-file@4.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Adding cordova-plugin-file-transfer to package.json
Adding the cordova-plugin-zip@3.1.0... 
Installing "cordova-plugin-zip" for android
Plugin dependency "cordova-plugin-file@4.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on android.
Adding cordova-plugin-zip to package.json
```

**Comment by ermik** [comment]
IMO, Cordova in general is known for being used across the version spectrum, so plugins tend to support older distributions for a long time,

**Comment by Sfinx** [comment]
Fixed this by this seq:

```
cordova create myApp1 org.apache.cordova.myApp myApp1
cordova platform add android
cordova plugin add cordova-plugin-file
cordova plugin add cordova-plugin-file-transfer
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-code-push
```

**Comment by jamesdixon** [comment]
Even though you've closed this, I'd love to know why this hasn't been resolved.

**Comment by alexcroox** [comment]
I too am having this issue. I need cordova-plugin-file 6.0.2 but this plugin keeps installing 4.3.3 when it gets installed....

**Comment by jamesdixon** [comment]
@alexandergoncharov yeah, still having this issue with the latest version

**Comment by HY1221** [comment]
cordova-plugin-file-transfer is deprecated and removed from Cordova 9. However, cordova-plugin-zip requires it.
